# Generated by Django 4.0.5 on 2022-07-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyectos',
            new_name='Project',
        ),
    ]
