# Generated by Django 4.0.5 on 2022-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_contact', models.IntegerField(choices=[[0, 'Contact'], [1, 'Complaint'], [2, 'Suggestion'], [3, 'Kudos']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
