# Generated by Django 4.0.5 on 2022-07-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
